CREATE TABLE SKILL_TYPES(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE SKILL_LEVELS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   PRIMARY KEY (ID)
);


INSERT INTO SKILL_TYPES VALUES (1, 'Hard skills');
INSERT INTO SKILL_TYPES VALUES (2, 'Soft skills');

INSERT INTO SKILL_LEVELS VALUES (1, 'Awareness');
INSERT INTO SKILL_LEVELS VALUES (2, 'Working');
INSERT INTO SKILL_LEVELS VALUES (3, 'Practitioner');
INSERT INTO SKILL_LEVELS VALUES (4, 'Expert');
